const word = [
    {'tube' : 'Toothpaste container'},
    {'seesaw': 'Up-and-down playground ride'},
    {'nightlight': 'Small lamp in the bedroom'},
    {'green': 'Colour of broccoli'},
    {'hinge': 'Joint on which a door turns'},
    {'toad': 'Frog-like amphibian'},
    {'trolley': 'Shop’s wire basket on wheels'},
    {'punnet': 'Tub for strawberries'},
    {'dome': 'Curved roof'},
    {'needle': 'Sewing tool'},
    {'eggcup': 'Small holder for a breakfast item'},
    {'apron': 'Cook’s clothes protector'},
    {'igloo': 'Snow house'},
    {'wick': 'Candle part that’s lit'},
    {'bizarre': 'Strange'},
    {'cuff': 'Shirt’s wristband'},
    {'antler': 'Horn of a deer'},
    {'penguin': 'Black and white Antarctic bird'},
    {'rattle': 'Baby’s noisy toy'},
    {'stairs': 'Set of steps'},
    {'easel': 'Artist’s three-legged stand'},
    {'slug': 'Slimy garden creature'}
]