const word = [
    {word: 'tube', descr: 'Toothpaste container'},
    {word: 'seesaw', descr: 'Up-and-down playground ride'},
    {word: 'nightlight', descr: 'Small lamp in the bedroom'},
    {word: 'green', descr: 'Colour of broccoli'},
    {word: 'hinge', descr: 'Joint on which a door turns'},
    {word: 'toad', descr: 'Frog-like amphibian'},
    {word: 'trolley', descr: 'Shop’s wire basket on wheels'},
    {word: 'punnet', descr: 'Tub for strawberries'},
    {word: 'dome', descr: 'Curved roof'},
    {word: 'needle', descr: 'Sewing tool'},
    {word: 'eggcup', descr: 'Small holder for a breakfast item'},
    {word: 'apron', descr: 'Cook’s clothes protector'},
    {word: 'igloo', descr: 'Snow house'},
    {word: 'wick', descr: 'Candle part that’s lit'},
    {word: 'bizarre', descr: 'Strange'},
    {word: 'cuff', descr: 'Shirt’s wristband'},
    {word: 'antler', descr: 'Horn of a deer'},
    {word: 'penguin', descr: 'Black and white Antarctic bird'},
    {word: 'rattle', descr: 'Baby’s noisy toy'},
    {word: 'stairs', descr: 'Set of steps'},
    {word: 'easel', descr: 'Artist’s three-legged stand'},
    {word: 'slug', descr: 'Slimy garden creature'}
]